{"name": "Если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "start": 1728215999453, "stop": 1728215999610, "uuid": "fa488354-755b-41d0-ada4-e8bbc9a96cae", "historyId": "d1cab6b93087c5ef26dafe71eda35ba4", "testCaseId": "d1cab6b93087c5ef26dafe71eda35ba4", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier_login_false", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WIN-4TEUO1LLUHP"}, {"name": "thread", "value": "12536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}